name: Keep Supabase Awake

on:
  schedule:
    - cron: '0 0 */4 * *'
  workflow_dispatch:

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase URL
        run: curl -I "https://zxpobxfcrhfkgipnqgad.supabase.co"
